# Generated by Django 5.0.1 on 2024-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('followers_amount', models.IntegerField(default=0)),
                ('following_amount', models.IntegerField(default=0)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='users.profile')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='users.profile')),
            ],
        ),
    ]
